# Generated by Django 5.0.2 on 2024-05-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=25),
        ),
    ]
