# Generated by Django 5.0.2 on 2024-05-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_alter_carro_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='color',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='marca',
        ),
    ]
