# Generated by Django 5.0.2 on 2024-05-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0003_remove_carro_color_remove_carro_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='modelo',
            new_name='color',
        ),
    ]
