# Generated by Django 5.0.2 on 2024-05-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0005_coche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coche',
            name='id',
        ),
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='coche',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='coche',
            name='marca',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='coche',
            name='modelo',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='Id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='coche',
            name='ID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
